apiVersion: v1
kind: Service
metadata:
  name: quant-webworks
  namespace: production
  labels:
    app: quant-webworks
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
spec:
  selector:
    app: quant-webworks
  ports:
  - port: 80
    targetPort: 8080
    name: http
  type: ClusterIP
