global:
  resolve_timeout: 5m
  smtp_smarthost: 'smtp.example.com:587'
  smtp_from: 'alertmanager@quantwebwork.com'
  smtp_auth_username: 'alertmanager'
  smtp_auth_password: 'password'  # In production, use Docker secrets or environment variables

route:
  group_by: ['alertname', 'job', 'severity']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 4h
  receiver: 'team-email'
  routes:
  - match:
      severity: critical
    receiver: 'team-pager'
    continue: true
  - match:
      severity: warning
    receiver: 'team-email'
    group_wait: 1m

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'instance']

receivers:
- name: 'team-email'
  email_configs:
  - to: 'alerts@quantwebwork.com'
    send_resolved: true

- name: 'team-pager'
  email_configs:
  - to: 'urgent-alerts@quantwebwork.com'
    send_resolved: true
  webhook_configs:
  - url: 'http://pager-service:8080/notify'
    send_resolved: true
