global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Load rules once and periodically evaluate them
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing endpoints to scrape
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "bridge-server"
    scrape_interval: 10s
    metrics_path: "/metrics"
    static_configs:
      - targets: ["bridge-server:8080"]
    
  - job_name: "frontend-metrics"
    scrape_interval: 10s
    metrics_path: "/metrics"
    static_configs:
      - targets: ["frontend-dev:3000"]

  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
