global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager-dev:9093

# Load rules once and periodically evaluate them
rule_files:
  - "alert_rules.yml"
  # - "second_rules.yml"

# A scrape configuration containing endpoints to scrape
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "bridge-server"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["bridge-server:8080"]
    
  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]

  # Database monitoring
  - job_name: "postgres"
    static_configs:
      - targets: ["postgres-exporter:9187"]

  # Redis monitoring
  - job_name: "redis"
    static_configs:
      - targets: ["redis-exporter:9121"]
